image: ubuntu:20.04

before_script:
    - ls
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata && apt-get install -y x11-xserver-utils && apt-get install --yes python3.9 && apt install --yes python3-pip && apt-get install --yes python3-tk
    - export DISPLAY=0
    - export MPLBACKEND='Agg'
    - pip3 install pipenv

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pipenv install --ignore-pipfile
    - pipenv run python3 src/main.py

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
